enum ConfigEnum {
  VISITOR = 'VISITOR',
  NEW_USER = 'NEW_USER',
  USER = 'USER',
  REJECTED_USER='REJECTED_USER',
  BLOCKED_USER='BLOCKED_USER',
  LC_UPDATE_INFO_APP = 'LC_UPDATE_INFO_APP',
  LC_UPDATE_INFO_WEB = 'LC_UPDATE_INFO_WEB',
  USER_TEMP = 'USER_TEMP',
  LC_UPDATE_INFO_CALLCENTER = 'LC_UPDATE_INFO_CALLCENTER',
  LC_AF_1 = 'LC_AF_1',
  LC_CANCEL_OVER_AGE = 'LC_CANCEL_OVER_AGE',
  LC_CANCEL_UNDER_AGE = 'LC_CANCEL_UNDER_AGE',
  CANCEL_UNDER_AGE = 'CANCEL_UNDER_AGE',
  CANCEL_OVER_AGE = 'CANCEL_OVER_AGE', 
  LC_CALL_1='LC_CALL_1',
  LC_UPDATE_ID_CARD='LC_UPDATE_ID_CARD',
  LC_UPDATE_AVATAR='LC_UPDATE_AVATAR',
  LC_ADD_PROFILE='LC_ADD_PROFILE',
  LC_APPROVE_VIDEO_1 = 'LC_APPROVE_VIDEO_1',
  LC_SEND_VIDEO = 'LC_SEND_VIDEO',
  LC_APPROVE_VIDEO_2 = 'LC_APPROVE_VIDEO_2',
  LC_APPROVE_VIDEO_3 = 'LC_APPROVE_VIDEO_3',
  CS_WAIT_DISBURSEMENT = 'CS_WAIT_DISBURSEMENT',
  CS_DISBURSED = 'CS_DISBURSED',
  CS_ENDED = 'CS_ENDED',
  LC_UPDATE_INFO_APP_RE='LC_UPDATE_INFO_APP_RE',
  ANDROID = 'ANDROID',
  IOS = 'IOS',
  LC_CANCEL_UPDATE = 'LC_CANCEL_UPDATE',
  LC_CANCEL_NEW = 'LC_CANCEL_NEW',
  LC_WAIT_SET_TIME = 'LC_WAIT_SET_TIME',
  CUSTOMER = 'CUSTOMER',
  LC_RESEND_VIDEO_1 = 'LC_RESEND_VIDEO_1',
  LC_RESEND_VIDEO_2 = 'LC_RESEND_VIDEO_2',
  APP_ACCOUNT_TEST_1 = '0375981250',
  APP_ACCOUNT_TEST_2 = '0333515848',
  APP_CCCD = 'Căn cước công dân',
  APP_CMND = 'Chứng minh nhân dân',
  APP_LOCATION = 'App',
  APP_AF_BACKEND = 'vndc-af-backend',
  APP_LOS_BACKEND = 'vndc-los-backend',
  APP_MOBILE_BACKEND = 'MOBILE-app',
  GENERATE_NEW_CONTRACT = 'GENERATE_NEW_CONTRACT',
  AI_CANCEL_RELATIVE_IN_BLACKLIST= 'AI_CANCEL_RELATIVE_IN_BLACKLIST',
  AI_CANCEL_IN_APPRAISING = 'AI_CANCEL_IN_APPRAISING',
  AI_CANCEL_IN_DEBT = 'AI_CANCEL_IN_DEBT',
  AI_CANCEL_LOW_SCORE = 'AI_CANCEL_LOW_SCORE',
  AI_CANCEL_NOT_IN_SYSTEM = 'AI_CANCEL_NOT_IN_SYSTEM',
  AI_CANCEL_NOT_VERIFIED = 'AI_CANCEL_NOT_VERIFIED',
  AI_CANCEL_RELATIVE_LOW_SCORE = 'AI_CANCEL_RELATIVE_LOW_SCORE',
  AI_ACCEPTED = 'AI__ACCEPTED',
  REDIS_TOKEN = 'REDIS:TOKEN:',
  REDIS_CHECKEKYC = 'REDIS:CHECKEKYC:',
  REDIS_IMAGE_UPLOAD = 'REDIS:IMAGE_UPLOAD:',
  LC_WITHOUT_UPDATE = 'LC_WITHOUT_UPDATE',
  LC_UPDATE_INFO = 'LC_UPDATE_INFO',
  PENDING='PENDING',
  VNDC_ALL='VNDC_ALL'

  
}

export default ConfigEnum;

export enum CacheExpiration {
  EXPIRED_FOREVER = 0,                  // forever
  EXPIRED_IN_MINUTE = 60,               // 1 minute
  EXPIRED_IN_HOUR = 60 * 60,            // 1 hours
  EXPIRED_IN_DAY = 24 * 60 * 60,        // 1 day
  EXPIRED_IN_MONTH = 30 * 24 * 60 * 60  // 1 month
}

export enum ConfigCheckAge {
  AGE_UNDER = 18,               
  AGE_OVER = 29,            
}
